### ISSUE TITLE
Use of official open source license?

### ISSUE THREAD

**Issue by AlbrechtL** [bruceoutdoors/DrawingApp#1]
Thanks for the great app!

I would like to use it as a base for my own picture draw app. It is possible that you re-license the code under a official open source license https://opensource.org/licenses?

For me any license is fine that is compatible with the GPL like GPL itself.

**Comment by bruceoutdoors** [comment]
As the README already indicates, do with it as you please.

The drawing app is originally some task that new comers of Materialise Malaysia have to go through as part of their training program. Because I was some short term intern then so I was exempted, but I did the project on my own anyway as an exercise to keep abreast with what the engineers there are learning.

Anyway the point is, nothing here is some production software that will accommodate millions of users, or even anything revolutionary.

I'd appreciate that you credit me though. (:
